version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_server

    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: strong123
      MYSQL_DATABASE: my_site
      