# Generated by Django 3.2.9 on 2024-05-08 13:43

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todoitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=todo_app.models.one_week_hence, verbose_name='Закончить к'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Сделано'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
