# Generated by Django 3.2.9 on 2024-05-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20240508_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='owner',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.todolist', verbose_name='Список дел'),
        ),
    ]
