# Generated by Django 3.2.9 on 2024-05-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Год')),
                ('january', models.PositiveIntegerField(default=0, verbose_name='Январь')),
                ('february', models.PositiveIntegerField(default=0, verbose_name='Февраль')),
                ('march', models.PositiveIntegerField(default=0, verbose_name='Март')),
                ('april', models.PositiveIntegerField(default=0, verbose_name='Апрель')),
                ('may', models.PositiveIntegerField(default=0, verbose_name='Май')),
                ('june', models.PositiveIntegerField(default=0, verbose_name='Июнь')),
                ('july', models.PositiveIntegerField(default=0, verbose_name='Июль')),
                ('august', models.PositiveIntegerField(default=0, verbose_name='Август')),
                ('september', models.PositiveIntegerField(default=0, verbose_name='Сентябрь')),
                ('october', models.PositiveIntegerField(default=0, verbose_name='Октябрь')),
                ('november', models.PositiveIntegerField(default=0, verbose_name='Ноябрь')),
                ('december', models.PositiveIntegerField(default=0, verbose_name='Декабрь')),
                ('total', models.PositiveIntegerField(verbose_name='Общий километраж')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, verbose_name='Месяц')),
                ('total', models.PositiveIntegerField(verbose_name='Километраж')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthes', to='run.year')),
            ],
        ),
    ]
