# Generated by Django 3.2.9 on 2024-05-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
