# Generated by Django 3.2.9 on 2023-06-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=140)),
                ('language', models.CharField(choices=[('rus', 'rus'), ('eng', 'eng')], max_length=10)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='read.year')),
            ],
        ),
    ]
