# Generated by Django 3.2.9 on 2024-05-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=140, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('rus', 'Русский'), ('eng', 'Английский')], max_length=3, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=140, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='read.year', verbose_name='Год прочтения'),
        ),
        migrations.AlterField(
            model_name='year',
            name='title',
            field=models.PositiveIntegerField(unique=True, verbose_name='Год'),
        ),
    ]
